name: Build Mod

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Unzip project
        run: unzip HybridCraft.zip

      - name: Show files
        run: ls -R

      - name: Setup Java 8
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 8

      - name: Make gradlew executable
        run: chmod +x forge-1.7.10-10.13.4.1614-1.7.10-src/gradlew

      - name: Build
        run: |
          cd forge-1.7.10-10.13.4.1614-1.7.10-src
          ./gradlew build

      - name: Upload jar
        uses: actions/upload-artifact@v4
        with:
          name: HybridCraft
          path: forge-1.7.10-10.13.4.1614-1.7.10-src/build/libs/*.jar
