name: Build HybridCraft

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Show files
        run: ls -la

      - name: Unzip project
        run: unzip "*.zip"

      - name: Show unpacked files
        run: find . -maxdepth 3

      - name: Setup Java 8
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 8

      - name: Make gradlew executable
        run: chmod +x forge-1.7.10/gradlew

      - name: Build mod
        run: |
          cd forge-1.7.10
          ./gradlew build

      - name: Upload jar
        uses: actions/upload-artifact@v4
        with:
          name: HybridCraft
          path: forge-1.7.10/build/libs/*.jar
